const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirts",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 56,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "This is high Quality Product",
    },
    {
      _id: 2,
      name: "Lacoste Slim Shirts",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 53,
      brand: "Lacoste",
      rating: 5,
      numReviews: 12,
      description: "This is high Quality Product",
    },
    {
      _id: 3,
      name: "Adidas Slim Shirts",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 59,
      brand: "Adidas",
      rating: 4,
      numReviews: 6,
      description: "This is high Quality Product",
    },
    {
      _id: 4,
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 140,
      brand: "Nike",
      rating: 5,
      numReviews: 11,
      description: "This is high Quality Product",
    },
    {
      _id: 5,
      name: "Lacoste Slim Pants",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 120,
      brand: "Lacoste",
      rating: 3.5,
      numReviews: 8,
      description: "This is high Quality Product",
    },
    {
      _id: 6,
      name: "Adidas Slim Pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 130,
      brand: "Adidas",
      rating: 5,
      numReviews: 15,
      description: "This is high Quality Product",
    },
  ],
};

export default data;
